spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/indoc
    username: indoc
    password: indoc
    tomcat:
      max-active: 1
      initial-size: 1
#      min-idle: 2
#      max-idle: 2
      test-on-borrow: true
      validation-query: select 1
  main:
    web-environment: false
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
